achievements_list = [
    {
        "name": "First Success",
        "description": "Finish a task",
        "criterion_type": "complete_tasks",
        "criterion_value": 1
    },
    {
        "name": "Unstoppable",
        "description": "Finish every task at least once",
        "criterion_type": "complete_tasks",
        "criterion_value": -1
    },
    {
        "name": "Top 50%",
        "description": "Beat 50% of players at any task",
        "criterion_type": "top_score_percent",
        "criterion_value": 50
    },
    {
        "name": "Top 25%",
        "description": "Beat 75% of players at any task",
        "criterion_type": "top_score_percent",
        "criterion_value": 25
    },
    {
        "name": "Top 10%",
        "description": "Beat 90% of players at any task",
        "criterion_type": "top_score_percent",
        "criterion_value": 10
    },
    {
        "name": "Top 5%",
        "description": "Beat 95% of players at any task",
        "criterion_type": "top_score_percent",
        "criterion_value": 5
    },
    {
        "name": "Top 50",
        "description": "Become one of the 50 best players at any task",
        "criterion_type": "top_n_score",
        "criterion_value": 50
    },
    {
        "name": "Top 10",
        "description": "Become one of the 10 best players at any task",
        "criterion_type": "top_n_score",
        "criterion_value": 10
    },
    {
        "name": "Top 1",
        "description": "Become THE BEST at any task",
        "criterion_type": "top_n_score",
        "criterion_value": 1
    },
]

task_by_difficulty = [
    # difficulty 0
    [
        "dkl sad dkl als faa falls kkk dal salk fas dkl ldl fall salal dds falla fallal kalka als lsd dak als",
        "asala jaffa asl fad flak flak lad ldl sass jak add fad asala ask kafka adad afl aas dafla dallas salk",
        "kafka flak dafla dada flak lld dds dkl sass ssa kkk dafla dafla salal dsl slask salk kafka falls afl",
        "lassa akka jfk sls flak afl jak ldl jak lld ada falls fda kafka dada salad salad als kkk falla fad alaska",
        "flask adad alfalfa ass akka fallal adad das slask fallal alaska akka salad dad kalka ldl dsl kkk als",
        "falla ask lld fallal ada asl jaffa salad dafla kafka ask flask jak sls lsd add fad akka kalka afl lsd",
        "kkk dkl dsl asala falls dallas dak fallal afl dada fda flak lsd ask lsd afl kalka dds das salk akka",
        "kalka flak dds lass lad dak sass all fas dkl ask afl jak dada slask dafla kkk dds fall add fas falla",
        "fallal dada sad kkk ssa flask afl das dak jak asl jaffa lad kafka jak flask ldl das fda ask fas afl",
        "alas faa kkk falla das flask das lsd dafla flak dal alfalfa ask add lassa ask slask dada fad fall afl",
        "alaska flask jak lld flask ldl jak ldl dada dsl flask fall alfalfa sls jfk das akka ldl flask dds fad",
        "flask dak salad alas alaska add dkl alaska fad kafka ssa ldl fda flak ass falls dak fda falla fallal",
        "jak fda ldl ass alfalfa fda fas dak asl kkk dsl dkl dsl jaffa salsa slask fad falla fad dada fda sss",
        "falla sad fallal sad afl lad salal flak lad kalka alas jaffa jak fda salad kalka sls lad kafka dafla",
        "ask lld salk adad falla dkl alfalfa dallas kkk ass adad sls alfalfa faa dafla fall dsl slask jak flask",
        "ask dkl kalka ldl dafla sss flak dada faa ass falla faa dafla ask falls das fall dada afl falls salad",
        "akka slask ldl dallas ldl alfalfa fallal alaska lad alaska dsl faa fda jaffa lld lass faa dafla fda",
        "salal afl kkk fas falls adad kafka jak salad flak sass falls dak dada add dak ask slask dds fas fas",
        "fall dada falls jaffa sas dsl sad jaffa dal dada dallas flak kafka dkl sas flask fda kafka lass dad",
        "kkk lad als salad ldl salad salk jak dada afl flak sss dafla fas kkk fas dkl ldl dada salk fallal asl",
        "kalka flask dak dsl das fall dds faa kalka sass ldl flak dada faa kalka alaska dallas add dds alfalfa",
        "kafka lad ask falls fda dal jfk sls dada fda flak asala dallas ask falls kafka dallas fallal jak jak",
        "dafla alas jfk dkl sass faa salad slask fall lsd fad akka jfk add falls kalka jaffa lad ldl fall jfk",
        "kafka lassa jfk dafla afl ldl dada flak alas salsa fda akka dada jak lass salk dkl flask dsl jak fda",
        "alaska lld dak sass jak fda dafla alaska fas falls slask das fda alaska jak dsl salk dal kkk lsd fall",
        "kafka afl ass sad sls lsd flask sad kalka jaffa fall dallas kalka ada das jaffa slask salad das dak",
        "salal dak falls flak lad falla salad flask akka salad dds dafla salk falla slask fda fda faa kalka alaska",
        "falla akka falls asala dallas ada afl salk jak afl add jaffa dak ask dak als add dsl fallal alfalfa",
        "lassa fad lld akka fda alaska akka falla fas jaffa dal salk salk dafla lsd sad alaska falls fda flak",
        "lld fas falls dallas alaska dkl fall alfalfa jfk lsd dak dallas dafla flask jfk kkk dds ask falls jak",
        "afl ldl fas dad dds dak fda aas dal faa slask kafka salad dak fad salsa jfk akka lsd jak asl fall fas",
        "lsd kafka afl lassa alaska sad jfk flask lsd fda jak dallas alfalfa dal jfk jak kalka lsd alfalfa ask",
        "fall salk jfk jfk lass jak falls kkk flak lsd dal fall dds ldl flask add fad slask dad slask das salk",
        "fallal lsd akka alfalfa asl jfk add aas flask jfk adad salk dak jfk sass salad dad alfalfa fda ask fad",
        "afl add als falla fas add lass akka jak falls alaska fas das falls ada jak fas kkk ldl afl kafka dsl",
        "salal alaska salad flak fall salk dafla alaska dds slask fall fad flask adad flask kalka kafka falla",
        "alas fallal dkl alaska fda ask faa dal falla flak falls dal ask jak dal adad asl jak salad akka jfk",
        "lassa kalka fda dds lsd falls fallal dak flak kafka alfalfa salk add lass ask dallas alaska sad slask",
        "fallal jfk jak salad salk dal flask sad alfalfa ada lad salsa jfk dad dak jaffa salk ssa fad flask kafka",
        "ask salsa jaffa dak alas flak als ldl alaska lld fda jaffa dsl flak dkl ldl akka adad alas dafla jaffa",
        "lld falls dafla sss jak jfk alaska dak dal fad falla fall sad flask sad fda flask akka flask add fallal",
        "alas jaffa fad dafla salk ldl jak jfk dallas lassa kkk dsl lad alaska dkl afl jaffa sas ask dada fallal",
        "sls kafka dada lassa jfk lsd alfalfa fda dds all fall kalka ask fad kafka lassa fad kalka flask ada",
        "lsd fda lad kafka sas afl fallal adad asl slask faa flak alaska kalka falla salk flak kafka slask ada",
        "ldl dafla dallas slask salk alaska kalka fallal falla fad afl ldl flask jak lld dsl flak dafla salk",
        "ldl kkk sass dad dafla salal faa fall dak faa akka alaska jaffa dafla dada dsl fas dsl kalka fas akka",
        "falla lad aas kafka salk das kafka jaffa sas sls add lassa adad salk fad fda salal fall alfalfa flak",
        "salsa flak sad flak dada alfalfa lsd salk akka jak dsl fall dallas salk lad jak jak dak salad dada fda",
        "alaska flask jfk adad kafka fad falla asala slask ldl flask dafla lad ssa dds faa dkl slask salk fda",
        "salsa alfalfa fda salk sad slask dak kalka dallas sad falls kafka adad fad slask flask fas lsd fda kalka",
        "lass ask das alas kafka flak afl dallas dad fas kkk afl dallas faa flak kafka dada sad afl ada falls",
        "ldl fda flask sas fda sls kafka kkk all salad lsd falls kafka lld alfalfa lad fad dallas faa salk alaska",
    ],
    # difficulty 1
    [
        "salal halakah flag alaska saga fas galahad adad dkg kashag akha dallas flak dahl alfalfa flak algal",
        "falls kasha hadj flag aga das flak haggadah fda hajj fsh algal das flag das half gsa dash dkg hakka",
        "ala dah khalkha fsh galahad jaffa sls algal gad slask gal kafka ada haj agal haggadah flash akha faa",
        "glass shag flak salk haggadah dak fsh afl dallas hajj jag khalkha gaff adad kashag dallas flash kkk",
        "salad ash skag kafka lakh dagda jaffa dhal glad allah gall fag ssa fahd khalka gaga shahadah akka salaah",
        "dal hajj gall shag dagda sas halakah akha slask alaska hadj jag dafla alaska dafla dag slask jak gafsa",
        "jak shahadah gaga falla halaka jag dds khalka dash fda gala slask aga half dkl gash shf fas lakh gall",
        "fallal lakh dsl akha kashag shag fag hdl flash dkg dak fall dagda jak sls haggadah falls akha faa kasha",
        "slash sag fall flak flask ash dallas fahd saga haggada dada ask dah salk dhaka jak skag galahad agha",
        "lsd lash lakh fsh flag dagga fad haggadah jfk khalkha shf slask flask gas hajj dds dag dhak dafla khalkha",
        "slag flash slask jfk khalsa gaff lld lhasa gsa dash fda kasha dash haj akka asadha fall dal saga gash",
        "fall dhak ash dhak shf hdl ask haggada dag salk glad ask fas gal fda jaffa gafsa alas fahd hadj dhak",
        "khalsa jfk hdl skag gall alfalfa dallas gal agha halakah fas lld asadha jak agha dhal falla dag fag",
        "flask dahl lag haggadah kalka lash dhak jfk lash sag faa lsd alfalfa lld haggadah fahd khalka ask sag",
        "salah haj gsa fda kashag salal kalka flak sad gash dagda flask hhs flask haggadah dash half afl gafsa",
        "gall shad khalka fas afl dhak dkg jak dagda lassa hajj gsa shf shf dag lakh aga ala hajj akha fag dak",
        "dhaka jak agal salk flag fallal lld sss lah lag hagada hakka fag fahd haggadah salaah kafka dahl das",
        "lad fsh flag hallah dkl hagada lass ask gag slask halaka gafsa hagada flash falla halaka jfk kalka jaffa",
        "lad jaffa flag dhaka akha gall khalka glass flash gala dagga saga jaffa dhak flask kashag agha kasha",
        "jfk kalka haggadah lsd sag gafsa dhak slask flash das fsh flash slag salk slag flak fahd dah gaga hadal",
        "alaska adhd flak hash alga saga fha shag salk shahadah akka fallal glad flask agha afl agal fas dash",
        "flak sash dkl dash fad flak saga dash galahad jaffa haggadah ala agha lakh saga half hajj hakka khalsa",
        "alaska adhd hajj halaka flag kashag gafsa dagda fha dkg lash flak slag flag faa halakah kasha fag hadal",
        "alga haggadah half gash dhak skag fallal falls jak alaska fha salad add kasha fall lakh haggada akka",
        "dhal alaska fag hadal haggada fallal als fag kasha hadj fag falls galahad hadj shag jfk salsa fad gash",
        "hadal dag akha ash khalkha hadj jfk faa ala aas dagda agal fda ash falls haggada gafsa salk fahd hajj",
        "lsd khalsa glass kasha jak dafla algal adh gall flag fas haggada faa adhd flash gaff dkl khalka dhak",
        "slask dagga khalkha dal aah jaffa jaffa dkl fsh dafla lag alas slask shahadah alaska haggadah flak shag",
        "fall salaah gal salad dash gag kkk jag hajj akka haj fall shad haggada hadal hash gafsa haj jag dal",
        "hall haggada flag shah flash asadha hakka alaska kafka hagada faa hajj fda gall dahl kashag haj dallas",
        "dsl haggada dak fsh jaffa salsa skag lassa fsh hajj dallas slask aga gash kasha faa dad hajj jak dag",
        "ldl ask khalsa falls flash haggada glass akka fsh hagada dada afl gaga alfalfa kashag lakh asadha dkg",
        "halal halakah dag skag gafsa jak haggada ldl als fsh akha fsh dafla halaka adhd gafsa dhak falls jag",
        "slask lakh gala dagga lhasa afl haj dada dak hakka agha gash gad falla als fag kafka galahad alfalfa",
        "gala dah fahd gas galahad kkk sas dsl kalka hash gas fag algal flask dallas fas kasha fsh falls dal",
        "falla jag add sash adhd halaka khalkha fallal agha falls dagga jaffa gash kasha agha fall dagda jag",
        "lag jfk salal dhal kasha flag khalka hadj flash shahadah afl flag gall dhak hadj fas kkk alga saga hajj",
        "dhaka lad hagada faa slash haggada dhak lad jaffa salad salk gall halaka halakah falla aga jag flash",
        "lass hallah kalka hagada gaff dal flag dahl jaffa jfk salaah agha glad gash lld shag dal hhs flask salk",
        "lash jag dag flash alfalfa hagada lakh dal slag halakah slask khalka asadha gafsa dkg glad dkg falla",
        "halaka algal hadj kashag shf sad gaff dada lassa akka gas afl halal hagada skag akha dafla kkk flak",
        "jfk dahl hallah flag hadj als kalka salaah gad fsh dagga fag kashag haj kashag gafsa dafla shahadah",
        "akka jaffa haggadah flag shah alga sls lad kkk dash hagada dhal sls half dak flask shf hadj gad fahd",
        "dafla fha galahad slask gsa fahd alaska salk gall khalkha gag fad galahad afl khalka hajj adh haj flask",
        "dhak flash dsl jag algal alaska hadj slask falla falls jaffa jaffa agha haggada das slask dkl salaah",
        "algal akha galahad gas lakh shahadah khalka salad gafsa fad fas kafka skag lad haggada dak fas kalka",
        "gala hall slask flag skag haj shahadah gad jag dak dafla jak fallal fda fda salad half jak haggada hajj",
        "lash slag dafla shah hag alaska fad saga kalka dag akha dal kashag dhak glad halaka aga ldl gafsa jag",
        "lash shag kalka asadha shf flag halaka aga hdl falla haggada slask dada khalka jfk fha alga ada jag",
        "flak dhal lass glass hals dag dafla khalka hadj gsa jaffa gas haj jaffa ask shag lld salk slask hagada",
        "gall agha jaffa akka ask kashag dak dkl dahl kasha haggadah gas allah dada shad gas dallas gaff dkl",
        "gal dhal afl akha falls sag lad fsh kafka dah dkl agha sass glad hadj kalka fha flak haggada lag flag",
    ],
    # difficulty 2
    [
        "tautly siris rashly justify stagily saturday dahl gaudy fruit husky uglify faddishly dark fugu gush",
        "audad star arugula lyly sitta hatful ark till kraut raj glia fha kuki juju hairtail satisfy disa faddily",
        "slushy iraki hurt flatly saida dkg usaf tight astir talk flatly thd ushas haj graylag khalkha disarray",
        "garuda rya flatus raffia djakarta gist silk hagada yautia tajiki saury gal shifty frilly juda hashish",
        "lilyturf skull shrill radially lastly rightful shaggily distrust fish lydia guardrail khat fistula ski",
        "stria airily strauss gushy fitful digit arak hit dak flutist stark ugly susah lsd llyr khi iga railyard",
        "gaud kalif austria third lyrist sissy shifty kalki ailurus athar sag jaffa ragusa huffy jaggy diuril",
        "talus islay iyyar fuji shakti guilt rash disa saga salk darky tush taffrail distally jugful rusk gulyas",
        "tahiti ataturk lustful jra shaggy skiff algid dika aril shifty riskily auriga gladly lithiasis daishiki",
        "tatu gari fill highly rakishly lygus audad juju riffraff guts kurus dastardly hula lasik tiddly kraut",
        "iga thirty hiatus till ajaia riyadh hurtful glia kahlua ladyfish urga fraud rasht grayly khaki stiffly",
        "fugly isurus ghat skulk irish futility ashur lustily skill fagus gaddi rajah fluidity urd shark tray",
        "hillary tarsal hajj gully fluffy rigidly gastritis hadal sikh tush skag rakishly tatu dal talkily hadith",
        "git hatful alright satyr sigurd skirl uygur khalif druggist kurd ulfilas fairy skilful dayfly stylishly",
        "iritis tuff irak alkali guildhall silty shaggy tidy faulty rusty tallish ark tidy urth fugu raid justly",
        "gasify starr kura gallia adit flush salk gladly dishrag gaul rat salutary karat salaah sassafras array",
        "ali gaud digital alir fatuity flush talkily asura hardly karat hit gaga riff sailfish satisfy distrust",
        "digitally firstly stalk jut araujia thalia iglu kauri laggard agathis fatalist usually faddishly tush",
        "frill durra gushy haj lulli lakh art kidd idyl gila just lastly jassid arak slay slaty fluky fully agathis",
        "sift hulky tallgrass flautist ritually staidly shah gat karakul fuggy friday sadist fistfight dusky",
        "dufy kirkia taffrail fight ragusa sightly jury hudud lutra glass slask slask fraught yardgrass falsify",
        "garuda sir glary tail harrisia rajah haussa frigid rask taif dkl hydra kyushu gruff kiddy thyrsus lark",
        "hill duly jujitsu gsr judas saturday haul kigali shaggily fur gujarat kudu yardgrass satisfy ulfilas",
        "luau faddily trad haiti garishly kaury dkg afraid likuta shirttail frailty futurist jurist flaskful",
        "august hilly july kirkuk taka fdr hydrus falla graffiti adh darkish gulu ashy glass giddily urth lyrist",
        "yurt huskily glia frigga shakti sardis raffia jaggary idyl girth duality rudra jihadi darkly krigia",
        "adrift glug raffishly alauda thirsty hajji grassy gallus jiddah giddily alight rightful alaska ritual",
        "gratis gikuyu lsd hall fistular taffy kalki shirr huffily sardis gaud justly thrash shtikl dalasi garish",
        "filariid kyd stray lightly kaury diuril jfk difflugia russia tutsi jaguar ajaia gildhall kishar ygdrasil",
        "luff lully fiat grail kalif shiftily isurus digit tsk ruth dysuria lauhala guff kittul yakut hilly hydrilla",
        "filth tsaritsa kafir guar guardrail kat aah assay jut shaky hudud adalia rightist luyia argyll shaktist",
        "jural tallith augusta flashy starfish kraft kasai hadj gauri tadalafil kid ladyfish lallygag kaki dairy",
        "tayassu alaska grill flash jyaistha dug khadi graylag thriftily taka flirt stud dutiful frigidly skagit",
        "tsarist halaka talus hug rightly falsity hadal kurdish rajah talkily haughty friskily sudsy hayrig salad",
        "susah digs fishily strait kiddy ghrf astragal urial dasyurid sikh flatly study friskily autarky kigali",
        "katari dull faulty liturgist ratify fright jirga arthur lld syria salaah duty hajj ask guar halaka friar",
        "daygirl gaudily tryst shirt fishtail usuli daftly rugulah dutifully dhak glis huffily jihad graffiti",
        "kraut sayda fishily gauss hurrah laugh stiff assiduity darkly tajiki daylight saki ufa urga hilar druggist",
        "tragulus lilith huji dryly jaggary aku sigurd arikara task fay affright kyushu jaghatai jafar silurus",
        "lily fakir sura jig surd tallgrass tuft alight ajuga kafir asadha highly kyat tully dasyatis airlift",
        "agility ritually fsh ilk sluggish alfilaria sulky flautist austral hudud tadarida skill jird jagua hadj",
        "litas duly khufu figural drift falsify thill skull sluggish hydrilla arity shtikl shag aku data haughtily",
        "fug tiflis turgidly halaka fright shirty faddily shirk ajuga jak rug hastily salad lush ataturk gushy",
        "rushy haggis alliaria sturdy autarky half fdr irtysh digitalis talks khalkha fatty sturdily stuffy kafka",
        "gusty riata rutilus jug shrift yalta judith duff rusty till thurify iraki guar kyd jaffar aright adrift",
        "guilt dufy rial thrash lyly slug kurta suslik auld frail ghrf dishrag study silkily autarky dak fruit",
        "rigidity adult kalahari daishiki jiddah yid filarial skulk jarful fishtail glass ritually rarity ratafia",
        "hiatus irk dayfly faustus rial augustus turk gilt flagfish dark hus gay dahlia garishly kali dural artfully",
        "gist yakut tilth hydrilla flirt hadj stagirus filarial gaud shirty fulah distally light tadjik faulty",
        "stir sassy slaty krakatau flash fugly raffish guildhall kadai arid fugly salk fight flush raj jiddah",
        "haji afflatus guardrail girlishly argufy latish faddist dryly sulky uakari ararat halakah kigali katari",
        "assyria adust sully irak gladly jaffa stay khalif farragut flaskful girlish turgid saltish radish harikari",
    ],
    # difficulty 3
    [
        "unfit bura tulu butyl tabuk nylghai vali sharia laid kris drag safari sin dialysis buttinsky fishgig",
        "bida vidal inning tar tuff babushka angrily ritually junta hannukah abkhas sugary najas tufa vilify",
        "truant nijinsky fishtail buhl laughing thb saying guru saturniid arrival viagra karsavina fahd adjutant",
        "skin braun gharry dingily gunflint handbuild thrash kurrat fun tab lysin tanbark uhf savara vulgarly",
        "unvarying fistful brusk filariid shakti juju abut brash friday assagai asian dali fitfully kgb labyrinth",
        "unlash vibrant killifish ybit disturb bang briskly justly drag vitally fuji irving skanky jinnah grinding",
        "tantalus tati kib arava stubbly bundling jarful liv shavian ninny thursday salting stinky frg rubbish",
        "hulking baffling lithiasis vibrant duty unsightly rain salving said tinkling trivial ibadan takin jangly",
        "highland bathyal bluing dika shiva isfahan karnataka fully lariat burka living nuytsia ganja huff vitharr",
        "slangy vagal slight fray huggins yank fluid haji balagan sunlit bragg arkansas ribaldry ungallant antitank",
        "jinni buff but ruffianly urth krigia slub bursary blinking dashiki buddhist andryala gas trying blank",
        "gratingly brilliant batik unhurt unfailing indignity hasdrubal buttinsky finland valvular baisakh gravy",
        "shanty villa nlrb built birling justinian flabby nijinsky turgid kingly signify faddish adjutant trash",
        "lublin latinist trunk tyndall thrilling livid grab junta frg king granary babushka vhf fittingly jilt",
        "nantua buna nudity insulting funk dura kharkiv balalaika bradbury trunkfish avidity straying halaka",
        "stab affinal byssus gavial stagirus furbish saddhu nab kirk vdu sinful yard vanda blastular tally huffish",
        "buskin stylist safranin fuji daylight vault vara taka jnd shag huskily harshly vitality birdbrain raffishly",
        "tantrist urga frigidity altair karat vilna tibialis grubbily nunavut baisakh jural habit fda ninny rankin",
        "guardant larva frill vibrissa jirga gary batting agha kandy thyrsus fall slub thriving unfunny hulking",
        "invading nigrify uub kandahar vitis bud flagrant luffa butyrin kirkuk tussah biddy villus sushi syringa",
        "baulk harikari livy sandglass kalantas btu vittaria sulfur ubykh lastingly faustian gavia aardvark filling",
        "bali taut slay unitard baklava dining hart thrifty skilly langur living laughably karsavina snafu sandbur",
        "lullaby kandahar hayrig bristly stifling rubus sauk jarring fantasist stinkbird vali brahui afraid harvard",
        "hansard sravana thinning sandfly stably khanty hindustan bushy dukas kvass laying raja britt argufy",
        "bright faintly burbank aid kishar gaunt araujia disunity avaritia drily fdr fail killifish galatian",
        "granular gravy saida thrilling gaba futility tibit skilful bunk vithar burunduki diary shuha fail adjutant",
        "stagnant stringy dba kalahari dust fugu bit dayan naja blushing vishnu djinny dufy ariana fusil jirrbal",
        "insist brass sangay davy fungia vulgarian lighting bag shandy jylland fatality inka nark gigabit austin",
        "staring urban irritably vitus djinny shirring skysail valiantly finish kandinsky buss skydiving hakka",
        "ailing alluring britain january kill tahitian standby asking faulty thirdhand unfitting gibraltar stink",
        "insignia stab bandy varuna filth adjust rangy brink fibril skylight gustavus jig valiantly kandinsky",
        "nigh bus shifting fry snaky falangist lviii bask dignitary rushy ajaia subdural kina digitalis hillbilly",
        "kib tank taurus gulu bally jaybird tailfin gingival blushful furnivall abidjan junky hinault radially",
        "hubbub latvian gunk sutura ninjitsu bilby fight dis raj kandinsky silvia flashbulb gayal anagyris ingraft",
        "lan flabbily gushy lansat arguably husk jabiru sinbad sitting varuna aku surfing lurid skinful akvavit",
        "balking stuart hillary guava innards handball firstly lutfisk vial brashly kalinin singly flat llud",
        "abnaki saudi frilly stiffly kinshasa billing futurist thrillful guiltily grind habakkuk sunday barnyard",
        "abatis hilus skank rightly latvia firstly instant uhland abulia akvavit alga kandahar fusain billiard",
        "nintu jhvh fishy airt handling kabul lustily birdbrain jagatai kgb fry david hannukah striving fraud",
        "aunty sanity affairs kulun visibly sang hydrilla tab dirk jaunty dishy gratify brandish hulky hiking",
        "blighty tankard husbandly kavakava shin draught blur jra sandfly vanbrugh birthing fat fundulus dufy",
        "ruin invalid garb gatt daily kafiri kalantas rakishly shagbark kurd shf rubbish astylar jfk land habitus",
        "indignity habitus rank bully faultily guru silky garish jiujitsu fin bandstand bvd sravana kusan naughtily",
        "nanking buyi talkily guttural vulgarian thill injury inrush dishful july variably kafiri abstain idun",
        "linaria bulghur baby brutishly junkyard dilantin jugful gravy trifid dika lallans tusk hag thurify ravishing",
        "radian funrun bisayan firsthand alsatian skinny gulag aba kuki savanna jung daishiki salvinia banting",
        "subshrub fri tailfin virus filly sugi skanda tasty knightly radial bruit juggling skivvy aditya rightly",
        "brandt butyl brink bhaga yhvh tantrist lutjanus taka vital frilly brig tussaud frugal kgb vittaria furry",
        "hyalin sugary sahib urth luvarus kuki grand infant uvular airlift hansard albanian hrvatska bat sayda",
        "rubus argun hydatid valhalla landfall baulk lividly adjutant jab untying kaffir indigirka vulval sirrah",
        "granth brigand burg nihility bavarian jungian tanakh viking transit funrun sully fistfight hadrian kaury",
        "finality bayard sudra nudnik harsh guild brunt viral davit shark knightia fluting vulval natty ibadan",
    ],
    # difficulty 4
    [
        "bruchus saclant khi midair vistula flag langtry guib abidjan maia mystify shirk scabbard vitals flick",
        "calvatia tibial jagganath urging vishnuism dick gambling summarily barnyard makalu charivari icky duchy",
        "juridic dardanian blastular trimmings khat gratuity fusain vivarium drub chassis nylghau arjuna titlark",
        "misalign juridic bangla malva rightish lift nattily claim turkish durbar vhf yardgrass richards irritably",
        "blackburn financing hungry dismaying buttinsky ravishing damaging slyly intifadah agamic uncivil vitalist",
        "caftan jimdandy blitt glumly sirdar racking bagdad munda shingling vulvitis tabuk hubris thankful scarily",
        "gamin churl branding grassy catty vicuna hafnium arrack fibril fuck sunday riksmal succubus javan langtry",
        "calidris fsb balarama rurality hatband bukharin dagda mismarry cubism alkaluria striving bullfinch briny",
        "curtal murkily nagi baykal allah aardvark fig shaggy cuff katmandu sassaby masjid sarcastic dravidian",
        "vicinal nystagmus dub marianas hairtail ruthful astrakhan statistic sibyllic skirting fun damask stubbs",
        "laudanum tuscany fatimah tardily cambrian vastly rank hurdling brutus vanity nagi skirl fatima sinclair",
        "crash rand mytilus hitchrack birr ningirsu vulgarian ginglymus bat jagua balkan gravida jaghatai carthamus",
        "lucy insular thulium balkan dingy flashcard valhalla gagman vali nautch starkly vicksburg jagannath",
        "abcs ding alnus dialysis lambkill suavity maryland full cygnus favus anti shiism crabs mulishly likuta",
        "infirmary buna arcadia cushitic russula kiddy cavum bultmann shrinking calvary saying buchanan jarring",
        "fulminant bura barmbrack lucy fauvism hill stinging barunduki grisly gynarchy misdating marking chitlings",
        "charadrii manfully tiff kannada braiding stairs luminary caring gibit visual skua richly unjustly vidal",
        "brummy vim birchbark labyrinth grad shrub infirmary kickback hatband millrun agnail thriving thirstily",
        "sabicu acrilan audibly valgus catalufa humulin strum bilk sully trackball skyjack mach augusta trf dag",
        "smithy salving cftr tuba backstay cynancum clinid carduus savara smirk alight trajan drifting bitch",
        "actuating slab maranta lyly mintmark lathi vali ranid viscacha byrd curitiba flutist milkman nga mirthful",
        "cambrian litmus viability haying fault kalantas distally sanctum akhbari masking navvy turbid fimbria",
        "scurvy lamisil ayin sandbur kilt chanty dubbing mustagh mudhif arak salving culinary calvinist djinn",
        "lilium tambac vulgar furan crayfish kitbag canary munda gavial barmbrack darsana shitty davy shabbily",
        "migrant kitschy divinity trismus chivalric surf hilar blushing hannibal hadji schmuck gambling jaggary",
        "uric tambac fanatism shavian muskat blissus rainy gantrisin tdt tyrannid stabling krishna fruity cyma",
        "grama rancidity uvulitis glib brickkiln haick numbly sulfuric bacchic dulcify naval umbrina distraint",
        "minimus racily diffract hanukah thb curing inability skintight dbms flatly dika lucifugal huamachil",
        "iambic cutch slangy friary kachin intifadah marang jaffa abulia clunk brand caucasia gunman brickly",
        "cjd myringa salyut calabash sifting drms titbit snuffly flick vastly friskily galbraith ambit fucus",
        "mainmast arbitrary cavil chukchi faisal hasidism mightily sunburn chukchi samarang larval trinidad fun",
        "musk acular sabbatum sadist naval casually anagrams futurity kyyiv matriarch isthmian garishly avidly",
        "affirm lucid nautch halab nimravus tangibly tadjik avifaunal llyr drafting jujitsu admiralty invisibly",
        "uncannily unsmiling babinski third jakarta sajama clavus atavism gaudy chiralgia birr cuff mutiny shivaism",
        "vaccaria bushbaby mundanity flagstaff kingly humbly saving farad mayfly bukharin jaunt cataflam skinny",
        "kami chairlift manubrium mismarry drinking alaric brama calgary hindgut caravan avadavat austrian butyrin",
        "cim brutally sardina avifaunal higi lbj clark calisaya stuart curium jury kandahar ivry glassy stimulant",
        "chantry lvi blacklist fumigant tsimshian bhutani sandbank myrdal clunking savant jinks canavalia khanty",
        "ablism fulica natta hrvatska bangla yay scald saktism burbank jauntily vainly bungarus stuffy shrubby",
        "lamia khan vlf jackal blank snuffling rings camshaft grudging gibit lyrurus tyr araujia lama cichlid",
        "fhlmc guiding vanilla barilla ninurta shrinking tardily tantrism chart brandmark stuffily judiciary",
        "siam straying billing simulcast luvarus smith huffing markka buckram sandril dirtying vitalist callas",
        "radiancy amish cufflink laburnum cathari tlingit brutality julian valsartan kurdish scudding ambiguity",
        "bunch shivah lynch narcist samarang backtalk jurist saladin gymnasium jain argasid frigid chabad gladly",
        "rama humanity flitch sink lvi skyjack abaft nimby dirtily sinning cultural blinking indian jungly curving",
        "facing cavum rigidify vicarial antrum chanukah fulbright snick mirky dilutant sluggish basidium babytalk",
        "dairymaid ruining cftr niggardly haiku bard lvii nicklaus fnma grub granitic hakham gigantism sambar",
        "characin alundum syntagm cannikin standby lgv finback sciara judith juju filariid acclaim brainy khalkha",
        "tammy sana charadrii hurting librarian bivalvia lufkin dairymaid takings sickbay janus fuggy jambalaya",
        "annum actuality basil ashram silks jabiru huggins carful faintly midland slack bandung syllabub licking",
        "ncdc miniskirt vanir gritty anthyllis bulla fairish midi bathyal tatu rickrack balaclava thinning filarial",
        "afflict mitsvah minuartia library making cataract saturday viand abactinal haida basilisk grimly bullyrag",
    ],
    # difficulty 5
    [
        "cationic ejection decayable simonise colander numerate berkeley categoric observed lutfisk corvette",
        "sedum gladness turkoman caff cervical globally dysthymia clubbish mekong hydrolith blank ravioli crossruff",
        "snitcher cloning vigilance isurus banneret humanism ranking boeuf harnessed romneya uglify slickness",
        "rangifer clubbing gadoid leaved musial hyaloid ulterior kami siccative trekker alcahest chrysaora filovirus",
        "manducate gorgon novel cockscomb sideritis shear hybridoma fibrosity burnt cheloid elkhound jive cardiff",
        "orach oriolidae bisect stammel clemency cancun vila grey flatulent borneo evildoing smallish highflier",
        "temujin flourish arcus bacillar buck ingress andalusia iago filthily cyanamide haji hostage totemism",
        "caducous tarsiidae urmia aviation treasury thrombose mullus carmaker hamburger clearance greave dummy",
        "diagonal loveless beatify jetsam snorer fueled gracility jeremiah bagful malecite virtu shouted cetonia",
        "arenaria cardiidae momot kabbala adjust ouachita macgregor fenestral molva vast judgment mayenne canary",
        "shithead menial incase bucharest subjoin horrify netlike gsr mattress salk haughtily drafting factoring",
        "incitive sunchoke cytolytic reserves freeborn sleigh offhand moderne abdominal unmanlike ballroom evacuate",
        "hellenism bankroll embolus grandly cuticula gravid acyclovir fellatio jem tinkle brutish forgive yarmulka",
        "unnerved sack closer bleeder genuine encaustic yardbird metonymy toehold fugo kettle gatherer vaulter",
        "halothane bitumen echolalia liveried myelinic jellify garamycin korean suntan bayonne caregiver hooker",
        "cichlidae thirteen oenomel dumbfound maulstick shivaism relay duckling serviette sunday garfield broadside",
        "unsaddle roomie blab kachinic insert segovia besseya minuteman artfully jesuitism dreadlock shingles",
        "crime overlie jujube undrained creditor stretchy stickily fha marini havelock garrulous bully comforter",
        "loved touched flavone krigia eibit mussiness dumbass nybble analects leukeran cyclosis chert femur viburnum",
        "simeon labour noncyclic stolid stocks hackamore gammon deference overbid guardedly inhume overshoot",
        "gluon hydrate ceilidh loving kingly hamster boeotia billfold smidgeon slivery nebula soja correggio",
        "alces takelma dooryard vase soundless abaya cushitic transfer legionary bordello malarkey chicken mottling",
        "coltish ground unlabeled malosma kirk family hickock abide relievo tycoon gastritis shelver montfort",
        "huge closing moist vacuole bolide crescendo stokehole ethically fright montane bettongia navajo banker",
        "khoikhoin condole overshot gumshield furbish halacha jug blacking daylong masher kettle reversal fillmore",
        "netmail birthrate mcmaster mummichog basketry jilt mouflon advisee ceylonite liven nganasan markov diversity",
        "croatia vasomotor cumfrey gardner kansan beach higgle goby hustler cocker divinity freelance bitterly",
        "dentition biramous sugarcoat arsenical loveable stachys foolery haematic verse blocky aigrette groak",
        "chlorine humus elegantly rubbish kobe jellify gulden diamagnet chufa savagery kiosk shovelful cfc brooklime",
        "certain strobilus fitment nylon fictive behold barunduki rhythmic stodge kriti guest mimesis calvinist",
        "siddons coruscate sunblind freyja mercator remark sukkoth ganoin bilobed coolly harte govern luvarus",
        "fuel visconti bootlace numerable mark monish droning division ready kindled hajji believing tayassu",
        "stegosaur collier believing knossos cryogen glochid allmouth mania flattened jitney vasiform caribe",
        "nonfatal laredo curtail telecom tubing disunify dinky triumvir fleabane coachman sleekly heterosis algal",
        "mandate tortilla cookstove buddy lodgement maratha reluctant fable baiting jargoon lutfisk ideality",
        "self donne dacha mightily blasting reedlike bruges fortress boulevard joist smitane checkbook fetology",
        "gerbillus sacristan choosy manihot rockiness fabulist antedon mole allergy birchbark jactation sheatfish",
        "colonist sienna imminency slav ratify biddy bluestem hargeisa rocker sue jasmine traverse uncouthly",
        "eocene boating remitment untired jealousy chug alveolar rambutan foreshock royalist knuckle jotting",
        "triune oscines mantell carnality mouselike gutenberg sheikhdom inflect revulsion garboard branchy force",
        "castroism ammeter labiatae indict heaven blurred rosemary highness firelock luting cymose siva factual",
        "nyssaceae gabardine ointment ulalgia hive jamaica furiously rabbi vesey overcook halyard adjudge forficate",
        "trundle advocate unbloody farmland doctorial coonhound moonlike steradian unbigoted rivalrous bunker",
        "sudation badgering tommyrot mahican javanese foeman calabura lasek satisfy marks kitsch bankhead alehouse",
        "decameter cogency honied turtler tabuk tardive manganese shambles insofar hogmanay lovebird oakley klavier",
        "electrum lamb francoa finished frankness vicia inerrancy judo marveller fealty cleavable kiang idaho",
        "sclera transcend muddled batholith blockade stay conjuring fiord biconcave aberrancy nave monandry amsinckia",
        "bleat juice romanal stalkless cycloloma legatee lorchel raft anagogic dust garbology cellblock shamanise",
        "malto isochrone tuber skimmer ovine undecagon liberty angevine mandatary jehad frick caff balsamic unitary",
        "carfare mendicant footfall teahouse averment homonymy boudoir agalactia subjacent keelboat volition",
        "bollard facia taenia blues enjoyer ovis truckle lightless alabamian majorca sorority egghead bartok",
        "agora linen backchat vulturine daybreak defroster mckim dubiety shah lucrative guarnieri ghettoise thymidine",
    ],
    # difficulty 6
    [
        "palaemon obeisance psyllium roswell aplanatic vividness uptick haifa eatage jolliet overtly wilful bursar",
        "planter trogium boiling sweeper yeshiva kroto picometre ducat thriftily befuddle vulpine darkness sondheim",
        "spoonbill eukaryote princedom hawkbit juncture housedog coville macon wicopy cuneiform revokable pageant",
        "snipefish oversew barretter babushka cocklebur manakin cyclicity sunbaked mange winey mips vaulted virginity",
        "pinter fragonard chiasmus bandolier profusely deerskin savoyard woven catawba jeroboam diaphysis brushwork",
        "hoosegow guardsman sockeye backstay picking pilotfish galveston hieracium arawak beep ovarian studbook",
        "edwardian nonmetal secale baobab sturnella slivery groak topically huisache envelop eyeshadow skimmed",
        "paternal frogmouth entranced amberbell thai scenery watertown lamarck acrophony thickhead cupping vitiated",
        "waif slovakian megahit doc mispickel basil trichina karyotype awesome umbrella albugo vitellus ruff",
        "plaything hordeum overarch blooded okenfuss owensboro cyprinus mandibula jessamine lawmaker ternate",
        "menippe fashioned content viii bilious sunscreen say hindshank wrester reggae gremlin bedhop cewa yobbo",
        "strawworm pneumonia bartholdi veinal outlawry podlike morning infection itch talkative sorbent sprag",
        "blackwash donnish archaism bechamel warpath temporary interrupt elvish beneficed fingered argument devolve",
        "swimmer glitch tango greenback grouch pussycat positive anthidium barefoot galvanic dray fijian winsome",
        "stupidly relay unbooked cobblers hedonism silva brownish dismaying pressman fount plowland crawdaddy",
        "weft croon seedman bloomer repayable bleu tinbergen ponka received wailful tahini veronese asklepios",
        "overlip cumber genuflect wingman ropemaker heyday invirase bruch jotting cotswolds gift elapidae necklike",
        "wireworm select pervasive ammonia moulding baldr maggoty cheekily pascha flimsily kibosh hachure propyl",
        "window sup mortar datemark nebuliser touchily fistfight prof noticed bedsore stability jaywalker surveil",
        "pedate whatever recovered msasa landrover laughing deanery riskiness snowbound pibgorn balefire multiple",
        "prophet myelogram clupeidae voidance crackpot boatload fink soloist numbat blowy guevara lower haemic",
        "richweed folio conclave continuum mulloway kichai gabor surfboard scarp venetia pupate wriggly barrack",
        "pollywog parch bobsled mali selsyn posture wok fieriness remedy diacalpa deciduous viewpoint moldavia",
        "phaius amoebic launch iffy golliwogg herculean goateed covenant sticky word mohave spirilla toynbee",
        "lipitor teddy socket prentice befooling caregiver moment aloud dphil brooch slantwise windless bourne",
        "wildfire margate evolution rockbound slaying plumed pommy dashingly cerebral obviously tupik notechis",
        "postiche edwards anguis baryon avionic berrylike misgiving mopping unwire sprit galbanum safety eyebath",
        "profanity nonmodern tocantins walleyed proturan cuba khat drugless savoyard manifesto hornbill proactive",
        "petcock prosthion mobius severance aryan goulash lawyer sandlike wader misdemean chaff abila muybridge",
        "witchlike mavik divine biogenous slapshot aruba jock refit doohickey swinging deprave melanism euphory",
        "phobos powder alfresco besmear banning unbeloved libertine fatuously wherry kindle meprin chinook magenta",
        "hyperopic snowboard palmar pursual adaption blackness cleave virginian shelfful leymus miscreant jaywalk",
        "spotter spillway cadmium mikania marvel sylph changed mumbai footprint bifoliate wireworm unknown typing",
        "wimble pose pesticide handbow griever wondrous livery roughneck enfilade greenfly artillery myogram",
        "option clapper camlan shakeable halevy chanukah nohow fervency populated stogy unwritten whammy juryman",
        "locoweed pismire blusher empty missive slicked owner guts vas nonimmune giraffa breaker hipless joust",
        "clipped mytilid showgirl groover ruggedise eventuate balinese panicky twirl trammel robotic klaipeda",
        "wifely goodly capsid aeonian ballerina martini pinky aureate shahadah moreover sweltry calosoma bata",
        "inaptness limekiln awaited paintable soiled cajanus locker violently trifling fifthly bruch armless",
        "panfish abalone hawkshaw craving religious macushla notoriety donut appendage ileostomy librium pushover",
        "clumping balletic colloidal recurvate ballpark always hubbub slowness masochism ftp enviable freely",
        "pothole townee presume unchurch novitiate bedpan underlay gorgas gadfly rickshaw iliamna bmdo dark suffering",
        "crowded spindrift abyss reductase impetuous pedology kaliph sweeping liniment contrived moveable oilfish",
        "podalyria terseness oculus primarily wafture ballyrag viburnum lychnis necklet fanwort likeness earthling",
        "hoper swoosh mono heretical unison nebbech agrypnia conker kovno sunday marijuana garfish atropos hail",
        "sapphire pentothal wembley fractious vodoun headlong amok hodoscope feedbag chevalier jellylike wordsmith",
        "capreolus asvina spawner moroccan clothier gdansk carpetbag hydrocele frey jesuitism gutenberg misgovern",
        "downcast dromaius entric bothrops guileless astronomy sokoro juke invisible plunder forlorn divergent",
        "operon cetacea bakeapple rainstorm unwished twayblade astrogate profile misally likuta handbill happening",
        "septal stoppered ciliata calamint rebutter bumpy wristlet flank shouter lodger delaware nonverbal blantyre",
        "lollipop motorless evans dumpcart sib kerchief dory jellied milage riding raw vayu catboat handsewn",
        "pikestaff chymosin twice euphemise backwoods flambeau stomper regiment viyella arranger vibration gemmed",
    ],
    # difficulty 7
    [
        "specious smell intro nonpublic pentoxide viva yucatan chinkapin shadow guarded fashioned juggling bentham",
        "upbeat oxybelis bolshevik hamelin anarchy weaving sclaff object seediness parsi humus breakup josh spawn",
        "phloem wahabi sciolist titian reversive hydra kine future ignorance alupent warmer catalexis amberbell",
        "plumlike playactor nourish texarkana bonney greave fernlike cowman shindig plywood botaurus missive",
        "spelunker forefoot bombast eyck victual handiwork gynobase parsons dawson oryx maniclike acervulus heresy",
        "precocity summery morgan lawman myxovirus about longhand shack fiendish jejunum puseyism probatory welsh",
        "paradigm disjoin pyle bruchus salix hit woodsman roadkill cornfield bosch vac jetty talkie galea defiance",
        "passable potage ramous bowse rocky unuttered carved silvern bookshop fruit executed fanweed mak spidery",
        "approved clown kibosh sketchily executant duma frigga hallowmas oboist darkly cohesive futile",
        "pleven fjord hume auspex vaccine abudefduf tyramine jewbush gossiping turkmen syncarp hydrolyse wetback",
        "hotpot bricole nowness vesicular popishly xenotime tinkling fairy acedia rumen abused howard",
        "biconvex manliness expertise gutenberg unshaken dylan sheatfish duckpin downright junk archive medullary",
        "ninepence lomustine thwarted smilax subeditor radiantly kurdistan assuage redshift devourer crampon",
        "upshot poephila extended japonica monkish mumble truancy twinkler fretful boomerang valiant bandsaw",
        "telex paintbox lawton classroom erinaceus lorry unyoke effluvium wharton dumbbell slovenija hesperis",
        "expiatory hominal bouillon subverter wormcast sphingid toadflax parjanya watteau brioche carnivora pyrogen",
        "prentice abalone emoticon virus chammy baikal whomp striking atriplex disengage effigy aware relieve",
        "plaster overnight ancohuma brothel fixation parakeet sanctity neediness wordsmith wallboard jhvh lour",
        "creeper orleanist weep remodel unrivaled cefobid babushka abyssal ringside exist exotoxin semiotics",
        "repast oestrogen nominate indirect xylosma aviatrix proud disembody vandyke pigweed arched footrace",
        "pdflp blackwood meg sedan innervate glucose adaxial symphony own plumbable grovel jitney viscacha",
        "patron soccer reminder hunchback whence yobibit cheloid anthrax sagebrush reflect alive foolproof woven",
        "porter sluiceway lastingly plasmid givenness buffeted teamwork clothes greenberg flummox wahvey",
        "craspedia trogium sensorium bandtail weighty villa oka footed pie highway jnr bugginess cupbearer centrex",
        "poyang addictive climactic gibibyte glow battler rubeola lxxii mithraic emulsify repulsion crowberry",
        "upholder minute precocity svalbard pullback abidjan correggio preachify newssheet claymore examine potluck",
        "updating meiotic worrier plumbago yearly vomer weekender chrism alexander caliphate tearful label lanky",
        "eupnoea downfall casework metonymic hevea burbling acalypha sleeved luxuriant krait hologram airfield",
        "pertainym clonic bilges caldwell vigorous kneeling anhedonia jihad exergonic kera penumbral wriggler",
        "ibex bonn upstart subscribe fisherman corvee columnist pliancy firewall shiitake polygon excoriate drinkable",
        "stipe transpose flatmate oxide mesonic comedown blush kera mayan adjudge concavely iberis overly sackful",
        "spearfish ramous schlep evergreen dexter nonviable tummy fernlike nuwc hoodwink amicably decalogue upanishad",
        "penniless hoka polymorph wolfe actuarial khedive mobula virgule wordily ascot jitney brandt exploited",
        "philippi notched mollymawk invoice brahmana europan swig wulfila strongbox jolliet paysheet governed",
        "plater complexly apnoeic  avertable laughable kraut shadowy twinberry remaking fenestral caskful",
        "nuptials bollard certainly germicide slowdown ceroxylon throwback conchfish jakobson beloved pager forcemeat",
        "deploy karma connors blain chaplin mutterer wristlet shindy fumbling deserved windbag expatiate stave",
        "probation peaty roomette coldness excision acaudate voiceless prewar hopi mailing wrecking beautiful",
        "axile hooey mangifera placed revenue sabinea dessert navajo pacemaker freeborn cuneiform extortion wyat",
        "pickaxe ecosoc manilla jonesboro drywall roughen bata ranker debrief ropiness hawfinch overture navajo",
        "placid newman ovine bethink ecumenism rippling kyphosis falsetto bjs cowled duct adaxially threonine",
        "patrick decoct roundsman warner hardbound markedly kylix flagon aviatress perfusion jaw bumelia flaxedil",
        "predation umbra rudbeckia patchwork coverlet taxonomer provisory powerful gloss belay mithan dioxide",
        "inspire samson cingulum body exiguity welsh jean takelma refilling parole ironwood rancidity cobblers",
        "sapience housefly index antimony hapsburg sliver indwell panicked extended newsroom verbesina causalgia",
        "upheaval brainwave most mystifier ctc styx twisting detriment krebs pay hydrous maulstick bogeyman judges",
        "biaxial wistfully skinhead ostracod hermetic phasianus antigonia grivet jejune hatchway asap leucotomy",
        "catalexis confect epical grapheme nobody boulevard setswana carsick catawba project geneve polygonum",
        "puccinia honeylike polysomy exporter civilly basify gloating decant duplex naumachia mirabeau swop batswana",
        "fireplace stepwise pearlwort bullion sometime delegacy jampack britisher chainsaw excused scurfy kilometer",
        "puncher alcoholic maui epoxy diverging deject crabbed ballcock feline exploiter wherry fumeroot essence",
        "bioscope kahoolawe nepotism overmuch holystone megapode swordfish xenograft underbid vapor gassy jesuitic",
    ],
    # difficulty 8
    [
        "carboxyl capek piemonte vulpecula blizzard agueweed mohawk fantan cast lexeme edgeways brahui intervene",
        "oxidize dramatics xerophyte thane overleap voracious micawber lignin goofy barkley bushwhack catalyze",
        "expound mesmeric forewoman bumpy nosecount varanus zarf betula subjacent hooker branding wane huxleian",
        "melospiza cirripede anosmia northwest harvey measured bestow kibbutz protology forget calycular pavane",
        "floozy plage homeobox insurable lettuce backfire twentieth mandola starve protozoa towboat vlaminck",
        "protozoic frankness warwick somalia overdrive cabalism assay unmanly haven grudge uxorious applejack",
        "gazelle palliasse krummhorn ascend birdlime wheat foolery bavaria apprize boatswain outmarch unavenged",
        "credenza dwindling goral mews dustpan beaner playback viaticus chrisom wolffish toxostoma expender leveler",
        "idolize dipole mumbai octopoda wavy beethoven percuss injectant coughing skew explain foetus fierily",
        "jynx peshmerga florist powdered pickle privilege shuha memorably zulu awaken thumbtack governing blazonry",
        "cannulize woolley swordplay pneumonia abuja histogram muscovite knifelike kerb flexeril vlaminck blintze",
        "improvize pelew censer beefsteak unitise ptyalin playhouse morgan xxxi madrono hazelwood francoa divalent",
        "monoxide prophet anorexic crucible swazi ayapana trackball envelope meleagris fortress shadowy ravel",
        "muazzin coalpit driblet heaviness leathery picket toxicity tragedy football wake widowman poivrade lutetium",
        "extrovert diplegia tumour wrenching metycaine bedspread pika floret fax whistle wbs jactation nuttily",
        "shegetz taxable seepage amphioxus finespun harvey piercing bucketful donnian wildfire zing bowie centrism",
        "zilch epoxy mange borax plywood toponym glaucoma foredeck knave midwife retrousse vertebral gluteal sandarach",
        "sizable ampere fawkes rewrite ocellated jumpiness pink headful kwacha gravida nairobi playbox evidently",
        "botox blip procuress between markhoor dragunov jerking zygote guayule adornment fetoscopy waiver exsert",
        "pretzel lobster fawkes hypertext suckle horsemint jocosely screaming jointed vitus welch boding lavalava",
        "cimex colpocele polymer swagger insurable stargazer kempt nightspot serfhood exuviae obscure freetown",
        "razmataz pastern partition mediatrix cloudy leave sputnik basinal schooner dunghill wasp signifier weariness",
        "sozzled tweet pappose cadastral tamarisk beatitude minority shivaism loaning downfall incline flexure",
        "homily fixings eastward placation handgun introvert catalyst hankering dubbin hazelwood duple expositor",
        "exudate premix hoops zikurat manis witless brambly kinase jnr fondue drivel caddoan workman fourpenny",
        "reflexive letdown disport thumping bellyache sacajawea khios embattled azo liv foxily exultant jump",
        "thiazide hepburn forswear clitocybe campeche convexly jamestown pagellus kakemono viscus shoji footing",
        "oaxaca pdl peri sexism lunchroom debug overland anomaly feisty zakat unsweet graz belie unswayed captivity",
        "chintzy moonwalk denebola achieve degust germanist separator forested toadflax solemnize nonpolar cowherd",
        "salpinx algometry esocidae befog pawl punning sheetrock lavabo wurlitzer jug mentor jezebel synovium",
        "expert sot cambodian wharfage immunise endozoic elephant doughy kilowatt salve djinni bigotry devote",
        "expectant compose weser belted penial vocaliser boltzmann interlude nebraska acth vigilant hymeneals",
        "zealous rhizopus majagua cecropia birken combative peristyle firenze antitoxic daumier vampire wedlock",
        "spizella spondias samoyede crural berra devilment exclusion roundworm blether pickle flossy coelogyne",
        "partizan workout tremble caledonia syphilis shavian brimming judaic lustfully whole cannulize adventist",
        "organize tapir welt hebraism ectoplasm acinus doggedly waive xylomelum checkout frog adaxial tribade",
        "parallax omissive clorox alizarin beanstalk pyemic nonuple tusseh mogadishu undefiled wailer jean blandly",
        "idealized pubertal sargasso subway catullus millrace ganymede chunky inducive fuze monoploid exult wallace",
        "micromyx principle brushing melanize sturdily bvd blanketed anywhere dishful theorize excrement exuviate",
        "reprize negotiant maddening finnic bristly cower pungently kbit feverous thighbone textile steinmetz",
        "xiv lewd dilation kameez pinna supposed offence physicist newborn mapping jig baryta revalue exuberant",
        "montez operatic buhl jeweled leniency exodontic dumplings vaccaria jerkwater fission cambial bairava",
        "desex weimar asystole chase haltingly piedmont brigid feudalize starved jowl warwick paranasal bossism",
        "hexagonal mazzini notecase owen upraise hymenal hark vermouth brunswick tempura doggie cowpea bookcase",
        "notarize bylaw aphorise neckband smallpox cementum anagrams ferocity vegetive gazette fluxion kin skreigh",
        "blazonry ample phonic adjective ungodly donetsk fissile narrowing casework mosander booboisie obviously",
        "sphinx itemize perejil laced garbage slantwise gunflint riksmaal gravure tawney otoscope derivable carex",
        "jerez chewink ignominy imposed vellicate blowfly alluvion unweary clxv ponka umbilicus sweatband soreness",
        "cxxx parathion eubryales timeworn pinkish whizzbang romanoff dispraise cheddar immunise secretory diviner",
        "calx furze boloney powderer rulership verifier dunkard huge djibouti exceeding camellia illative sumptuary",
        "pixilated astrolabe kilometer vetch watergate neuritis majorette iguazu slaphappy flatware grouchy cornbread",
        "wyszynski penalise uniform microglia explicit verminous turbid cherubic firing lawlessly viscera docket",
    ],
    # difficulty 9
    [
        "lanzhou epidermic whittle keftab avidness cox seaquake maigre yavapai atrazine najas pyrexia bracteal",
        "fez opt prawn math heretic grouping whisper bromide pityingly saltworks prolix squelch slavish imbiber",
        "marbleize expurgate focal conflict swearword shoaly skyhook activist pizza  equably plumiera hesperian",
        "metazoan requite spinus dominick bountied express whizz flamingo worthily jackfruit valise bismark driveller",
        "floozie unadapted tweeter echium asexual boltzmann necrology silvery prick quiz ototoxic rowdily expound",
        "blintze proconsul horsewhip lambda homeobox sprucely tequila kept globalise pij gorbachev penalize fixture",
        "cognize pied welkin thymol birdlime vesuvius queens jagatai duffle quat coupling week ashbin axiology",
        "mechanize chipping walesa labourer taxodium militancy venally jumbal jerkiness zama foldout quad waxwing",
        "squealer kidnapper wisecrack ghostlike ischium cabaret nietzsche endotoxin earthly faintly scrivened",
        "zinnemann putsch sideway transport fallboard squire askew reserved plangent expiry gujerat sexiness",
        "lazybones excessive punchball drms tricolour frequent korzybski goatherd keflin triplex lawgiver mealberry",
        "zettabit deplore allowable monorail poached bivalent intuit chequer pallidity unchecked galbulus front",
        "pulque stonework mealberry salpinx tricot inductive emphasize shortfall juarez mugilidae busywork livonia",
        "anasazi escaped drew soricidae adamant innoxious workbook inquest devolve hook beluga doyly flattened",
        "unmuzzle sapote warlpiri adduce morbidly inweave koranic skoplje anchovy knox jiffy zarqa badmouth",
        "frizzle picometer wreckfish morgan beset nasdaq regulator vioxx frumpy woodchuck tribesman majesty prove",
        "liquify politick wifely waxycap uppermost lucidness walkover ejector sheaf empathize gcse indexing variolar",
        "squeamish complect texas fastener wolfman loveseat wary lespedeza jerevan ballpen macroglia pipework",
        "zend inspiring inward apogean swimming congridae bumbling quine overbold tank jahvey falsehood moresque",
        "lacquer dynapen mixology hautboy beltway squeaky akvavit jewbush fish prone amorous necking zambian",
        "quran campsite stoneware waxflower guzzler royal tastebud babushka virga araujia statewide epochal delusive",
        "arborize splice hawkbill trimmer organizer privateer furane synergist ondaatje quebecois acervulus annualry",
        "mashriq partizan antimonic alectoria kinswoman gloxinia styrax lgb nectary vagal donate fergon itemize",
        "nietzsche salix gowned petalled bruno dairymaid becket exquisite heartleaf jacaranda voiceless speck",
        "monazite ovalipes downswing consignor bidder sunk intensity unsexy ploughing liquorice outfall jowett",
        "tarzan quail odets symbolist sixthly plethoric oven kobe foldout straggle hazardia prolix whetstone",
        "eternize possum bisque swbw holcus civilian lycium locker rogation watts joyful tamandua probably",
        "tequila zooid sexualize camassia nonce depone superbly slantways dickey urchin ambages privates reforest",
        "zeppo webcam unsung halcyon theresa bollocks jimenez loafing goldsmith quake anxiety valance",
        "ramequin midpoint fraxinus balanced thieving rummy lewdly baptize okeh fizgig dextrin deadwood eolithic",
        "cortez coupler expiative midland fumble decay hancock bewray shenyang zagreb max clerihew outrival qatar",
        "hijab mopper apoenzyme boutique abkhazia verdun lexington folly jawed kisumu cocoon sublimity ovoflavin",
        "selznick persia meow abashment leaving soundly epitaxy bluffly pyxis nimitz caranx pow vulcanite enquire",
        "puzzle bollworm eumycetes enamor primeval squint leek furthest tilling decease exhaust bandwagon corvidae",
        "thorazine spiritize whiptail apothegm locater durable faquir activist barbary axile kymograph conjury",
        "equipment saw solandra compress abruption unavenged corozo enology rocklike hayrick flaps jesuit mackenzie",
        "isoniazid anaspid tarweed ampersand icsh bolt verbalism cumana trumpery worker quirk buxus bagatelle",
        "juarez proofread vioxx loathsome icelandic swine supremacy banjul link pekingese batfowl quicky sazerac",
        "lazio speed ribwort dicumarol melanise siliqua cockade heaving preachify cicatrize adjourn crax whack",
        "deodorize masqat limewater headland busker overfeed atriplex lycium pongamia jennet amazed luxate weeper",
        "squeamish scope pauperize reflexly herewith kinglet baker dixieland jointworm percher baiomys",
        "zion napu galway canberra exegesis trumpets vetchling burke poriferan mikmaq rigidness sexed",
        "agaze putrajaya squabby plumpness expired slick cabin scoffing hayrack shoebox weakfish guangzhou manihot",
        "ouzel harpullia whitey fumed contort biscuit medevac babelike quibble seizing breadbox abjure waxwing",
        "resize excel pallas leukoma aquinas sellable oversea sawdust jassidae hebdomad couthy stalinize effects",
        "cadiz propanol sioux bookplate mortify welcoming jet cogwheel quietude carboxyl euryalida moldova silver",
        "zealand pocked iroquois kiliwa minefield turboprop pehlevi depict contagion jensen pizzeria willies apomixis",
        "champleve flywheel necessary donizetti squawk arbitral grison zirbanit join pressman ovine dak",
        "merozoite subspace moorfowl dusicyon celecoxib quad kovno abnegate headrace jarring zamia polemical",
        "coquet apoptosis witloof cladode mem reading bugleweed luxemburg naumachy vizsla milkshake jobless vientiane",
        "embezzled apparatus endotoxin fuqra wrangling sturdily vender abkhazian woodfern mujahid leuctra lvii",
        "arizonian orpin indexer bloomer aphakic washtub briquet perceive jump territory wigmaker foray zap ",
    ]
]

complexity_levels = [
    "asdfjkl ",
    "asdfghjkl ",
    "asdfghjklrtyui ",
    "asdfghjklrtyuivbn ",
    "asdfghjklrtyuivbncm ",
    "asdfghjklrtyuivbncmeo ",
    "asdfghjklrtyuivbncmeowp ",
    "asdfghjklrtyuivbncmeowpx ",
    "asdfghjklrtyuivbncmeowpxz ",
    "asdfghjklrtyuivbncmeowpxzq ",
]
